	<div class="section">

		<div class="section-inner">
			<div class="faq-sidebar">
				<div class="sidebar-link"><a href="<?php echo base_url('faq'); ?>">All FAQs</a></div>
				<div class="sidebar-link"><a href="#">Full Buy</a></div>
				<div class="sidebar-link active_link"><a href="<?php echo base_url("pool-buy-faq"); ?>">Pool Buy</a></div>
			</div>
			<div class="faq-mainbar">
				<div class="each-container">
					<div class="acordion" id="one">
						What is Buy2Let Pool-buy? <i class="fa fa-angle-down"></i>
					</div>
					<div class="acordion-content" id="content-one">
						
                    Buy2Let Pool-buy is a smart way to invest in fractional interests of a property while giving investors full freedom from time-consuming operating responsibilities, such as property and tenant management. In its unique structure, properties are held in trust and shares are issued to investors. 
                    <p>The structure entitles the investor to receive quarterly cash distributions of the property’s net rental income, after deducting property maintenance and management expenses.  It enables Buy2Let to manage and service homes directly, so investors experience a managed, hassle-free investment intended to limit potential investor liability. </p>


					</div>
				</div>
				<div class="each-container">
					<div class="acordion" id="two">
						Who can participate in Buy2Let Pool-buy?<i class="fa fa-angle-down"></i>
					</div>
					<div class="acordion-content" id="content-two">
					    Anyone may review Buy2Let Pool-buy properties. If you decide to own a share or multiple shares and initiate the investment process, you will be required to sign up and complete the Buy2Let investor profile. 

					</div>
				</div>
				<div class="each-container">
					<div class="acordion" id="three">
						How does a Buy2Let Pool-buy investment work? <i class="fa fa-angle-down"></i>
					</div>
					<div class="acordion-content" id="content-three">
						Investors select a Buy2Let Pool-buy property and acquire fractional interests that represent an ownership interest in that property. The investment is designed to deliver passive income without management responsibilities.
						<p>Once Buy2Let receives your payment, your share(s) will be allocated with a certificate of allocation and you will be entitled to receive quarterly distributions of pro rata net rental income (rents minus fees and expenses after the 1st year, excludes property management fee) generated by the property. Buy2Let Pool-buy handles operational responsibilities.</p>

 
					</div>
				</div>
				<div class="each-container">
					<div class="acordion" id="four">
						How does a Buy2Let Pool-buy investment compare with buying a rental property on my own? <i class="fa fa-angle-down"></i>
					</div>
					<div class="acordion-content" id="content-four">
						Direct ownership is appropriate for those who prefer more direct control and have the financial means to do so. Our aim with Buy2Let Pool-buy is to lower the entry barrier to real estate investment, eliminate the need for investors to deal with loan applications, a lengthy closing process, property management and potential landlord-tenant disputes and to avoid agency fees and closing costs. Buy2Let Pool-buy is intended to be a truly passive income opportunity as the home is fully managed by Buy2Let, but more, it provides an opportunity for investors to enjoy good appreciation on the asset/investment annually.
						<p>Full ownership (Full Buy):  You are the sole investor in the property and own 100% of any potential returns. Investors select a Buy2Let Full-buy property and acquire interests that represent a direct beneficial ownership interest in that property's economics rights by:
						    <ul>
                                <li>paying 100% of the home price plus fees in cash or</li>
                                <li>paying a percentage of the home price in cash as down payment and utilizing Buy2Let financing options  i.e Mortgage or Payment plan</li> 
                            </ul>
                        </p>

                        Fractional ownership (Pool Buy): On select properties, investors can purchase shares representing 1/20 ownership in the economic rights to an underlying property. Each share is allocated the equivalent fraction (1/20) of the total rental income, and total expenses associated with the home after the first year, exclude property management fee. 
 

					</div>
				</div>
				<div class="each-container">
					<div class="acordion" id="five">
						Who manages these Properties? <i class="fa fa-angle-down"></i>
					</div>
					<div class="acordion-content" id="content-five">
						
						Buy2Let professionally manages its properties through its partner, RentSmallSmall, a property letting and management company. Property/Asset maintenance is also performed by a professional, in-house team of experts focused on optimizing the long-term income potential of each property.

					</div>
				</div>
				<div class="each-container">
					<div class="acordion" id="six">
						What are the associated fees and expenses charged by Buy2Let?<i class="fa fa-angle-down"></i>
					</div>
					<div class="acordion-content" id="content-six">
						
                        <p>The purchase price covers property maintenance, land-use-charge, and insurance fee for the first year, excluding property management fee. 
                        </p>
                        From year 2, Buy2Let Pool-buy charges ongoing operating fees that are deducted from rent cash flow prior to any cash flow being disbursed to the investors. Each investor receives his or her pro rata share of any net rental income and is responsible for the pro rata share of the property’s operating fees and expenses. The property’s fees and expenses consist of the following:
                        <ul>
                            <li><b>Property Management Fee</b> – Equal to 10% of gross rent and other income. This is an “all-in” fee that includes costs such as letting fees that are normally charged separately by other property managers.</li> 
                        
                            <li><b>Property/Asset Maintenance Fee</b> – The property maintenance fee is set at 10% of the gross rent. This fee may be adjusted based on actual cost but a detailed report will be submitted with breakdown of expenses.</li>
                        
                            <li><b>Land Use Charge (LUC)</b> – The property is classified as Residential Property, without Owner in residence. The annual LUC rates applicable to this property is 0.394% of property market value. The property manager will estimate the annual LUC to be paid on the property. A pro rata portion of the annual LUC will be deducted from each quarterly distribution before any amounts are distributed to owners. Any deviations between the property manager’s estimates and actual LUC liability will be reconciled yearly.</li> 
                        
                            <li><b>Insurance Fees</b> – The property manager will obtain property insurance on each property at institutional rates that it believes are competitive. Insurance policies will cover damage resulting from fire, flood and other standard items.</li> 
                        </ul>
                        Certain other fees, costs and expenses may be deducted from time to time as necessary for the operation of the property.

					</div>
				</div>
				<div class="each-container">
					<div class="acordion" id="seven">
						How does Buy2Let Pool-buy make diversification easier? <i class="fa fa-angle-down"></i>
					</div>
					<div class="acordion-content" id="content-seven">
						
						Buy2Let Pool-buy enables investments in properties starting at N200,000 per share. Not only will this make real estate investing accessible to a much larger audience, it also enables investment diversification across multiple properties for far less capital than what is traditionally possible. 
						<p>For example, if shares in four separate homes were priced at N200,000 per share in the first home, N300,000 per share in the second home, N400,000 per share in the third home, and N500,000 per share in the fourth home, you could purchase one share in each of the four properties for a total investment of only N1,400,000 and be diversified across four properties.
						</p>

					</div>
				</div>
				<div class="each-container">
					<div class="acordion" id="eight">
						What about other investors in the same property? How do they impact my investment? <i class="fa fa-angle-down"></i>
					</div>
					<div class="acordion-content" id="content-eight">
						
						Investors in the same property typically do not affect each other’s investment. The ownership and operating structure is such that Buy2Let manages all operating and asset decisions on behalf of all shareholders. Investors interested in exiting can list and sell their shares only through Buy2Let at fair market value.


					</div>
				</div>
				<div class="each-container">
					<div class="acordion" id="nine">
						What is the term of a Buy2Let Pool-buy investment? <i class="fa fa-angle-down"></i>
					</div>
					<div class="acordion-content" id="content-nine">
						
						Buy2Let Pool-buy investments are intended to have indefinite terms. Unlike some other real estate investments, there is no set end or maturity date at which the investment is dissolved. The Buy2Let Pool-buy structure is intended to keep all properties within the program for as long as possible, but if an investor wishes to exit the investment, the shares can be listed and sold through Buy2Let platform at fair market value.

 
					</div>
				</div>
				<div class="each-container">
					<div class="acordion" id="ten">
						What happens if I can’t find an investor to buy my shares when I want to sell? <i class="fa fa-angle-down"></i>
					</div>
					<div class="acordion-content" id="content-ten">
					    We advise that you list your share(s) at fair market value if you want to sell really fast. However, if you don’t sell in 7days, we will buy back from you and we will apply the guaranteed appreciation to the purchase price or we buy at fair market value if the 12months cycle is not completed in a given year.

 
					</div>
				</div>
				<div class="each-container">
					<div class="acordion" id="eleven">
						What Criteria are used to select Tenant? <i class="fa fa-angle-down"></i>
					</div>
					<div class="acordion-content" id="content-eleven">
						
						
                        Our partner, RentSmallSmall has established a vetting process for selecting tenants.  Selection criteria include:
                        <ul>
                            <li>Credit rating</li>
                            <li>Earns monthly income at least 3 times more than rent</li>
                            <li>Background check (employment status included)</li>
                            <li>No recent bankruptcies, evictions, and landlord disputes</li>
                        </ul>
 
					</div>
				</div>
				<div class="each-container">
					<div class="acordion" id="twelve">
						Does Buy2Let own these Properties? <i class="fa fa-angle-down"></i>
					</div>
					<div class="acordion-content" id="content-twelve">
						
                        Title for the homes is held in trust by Buy2Let, and administered by Buy2Let on behalf of investors. This structure enables Buy2Let or its affiliates to perform operational duties such as professional in-house property and asset management, while allowing investors to maintain an economic interest in the underlying home.
                        <p>Should an investor want to take direct ownership of a property, the investor will have to buy shares from other investors if they are willing to sell. Alternatively, the investor can diversify and buy shares in other properties. Also, investors can convert shares across multiple properties to a single property of equal value. </p>
 
 
					</div>
				</div>
				<div class="each-container">
					<div class="acordion" id="thirteen">
						What is the condition of these properties?<i class="fa fa-angle-down"></i>
					</div>
					<div class="acordion-content" id="content-thirteen">
						 
                        All properties on Buy2Let are carefully hand picked to provide high return to investors. These properties are either new construction or renovated to a standard intended to enhance rental income and enjoy good appreciation. 

					</div>
				</div>
				<div class="each-container">
					<div class="acordion" id="fourteen">
						How is the annual distribution for a Buy2Let Pool-buy investment determined?<i class="fa fa-angle-down"></i>
					</div>
					<div class="acordion-content" id="content-fourteen">
						
						Your annual net cash flow on a Buy2Let Pool-buy investment is the estimated rental income, minus all expenses such as property insurance, property and asset management fees and land-use-charge.
						<p>Distributions may increase or decrease over the life of the investment based on numerous factors, including, but not limited to, property and asset management fees, land-use-charge insurance fee, repair, maintenance and capital expenditures and other fees, costs and expenses. There may be quarters when there is no cash available for distribution if cash is needed to fund costs related to the property.</p>

 
					</div>
				</div>
				<div class="each-container">
					<div class="acordion" id="fifteen">
						What is the investment process? <i class="fa fa-angle-down"></i>
					</div>
					<div class="acordion-content" id="content-fifteen">
						
                        To invest in Buy2Let Pool-buy: 
                        <ol>
                            <li>Select – Choose your property and the amount of shares you’re interested in.</li>
                            <li>Verify – Complete buyer’s profile </li>
                            <li>Pay – Complete your purchase using our onsite and secured payment gateway</li>
                        </ol>

 
					</div>
				</div>
				<div class="each-container">
					<div class="acordion" id="sixteen">
						Who performs the property inspections and how are inspections done?<i class="fa fa-angle-down"></i>
					</div>
					<div class="acordion-content" id="content-sixteen">
						
						We have experienced property inspectors to show you around and answer any questions you may have. You can schedule inspections using the “Book Inspection” tab in the top right corner of the property page. You can select date and time and a team member of Buy2Let will confirm via email and place a call through to you.
 
					</div>
				</div>
				<div class="each-container">
					<div class="acordion" id="seventeen">
						How long can I hold my investment? <i class="fa fa-angle-down"></i>
					</div>
					<div class="acordion-content" id="content-seventeen">
						
                        There is no minimum hold period for a Buy2Let Pool-buy investment. You can list and sell your shares whenever you want on the Buy2Let platform. There are investors looking to increase their share interest daily. If you don’t sell after 7days of listing, Buy2Let will buy back from you and apply its guaranteed annual appreciation on the price you paid to acquire the shares. If your investment has not completed a 12months cycle in a given year, a fair market value will be determined. 

					</div>
				</div>
				<div class="each-container">
					<div class="acordion" id="eighteen">
						When will I receive rent distributions? <i class="fa fa-angle-down"></i>
					</div>
					<div class="acordion-content" id="content-eighteen">
						Investors will receive quarterly reporting outlining the performance of the investment during that time period. Distributions coinciding with the performance during that quarter would be paid on the 15th day of each February, May, August and November, assuming they hold their investment on the immediately preceding December 31, March 31, June 30 or September 30, respectively.
						<p>After the initial purchase of an interest, your distribution will be pro-rated within the quarter for the amount of time you own the shares.
                        </p>

					</div>
				</div>
				<div class="each-container">
					<div class="acordion" id="nineteen">
						What documents will I receive as an investor?<i class="fa fa-angle-down"></i>
					</div>
					<div class="acordion-content" id="content-nineteen">
						We intend to provide you with transaction documents, investment certificate, distribution reports, property and asset management updates.


					</div>
				</div>
				<div class="each-container">
					<div class="acordion" id="twenty">
						How will I be updated on the performance of my investment? <i class="fa fa-angle-down"></i>
					</div>
					<div class="acordion-content" id="content-twenty">
						
                        Buy2Let intends to send reports on the performance of your holdings on a quarterly basis. In the future, investors should be able to check their holdings and performance on the Buy2Let platform.
 
					</div>
				</div>
				<div class="each-container">
					<div class="acordion" id="twentyone">
						What if something happens to the home, such as a natural disaster?<i class="fa fa-angle-down"></i>
					</div>
					<div class="acordion-content" id="content-twentyone">
						By purchasing interest in any of Buy2Let property, an investor will be deemed to consent to the property manager obtaining insurance on the property. The premiums for insurance coverage will be deducted from quarterly distributions.
						<p>Insurance policies will cover property peril and potential damage resulting from fire & lightning, explosion, aircraft & vehicles, vandalism & malicious mischief, glass breakage, falling objects, theft, and smoke. The coverage will not cover potential items typically not covered by property insurance such as damage resulting from mold, power failure, neglect, seepage and/ or pollution, government action or other damage typically not covered by property insurance.
                         </p>
					</div>
				</div>
				<div class="each-container">
					<div class="acordion" id="twentytwo">
						Is the property periodically re-valued, and if so, how often?<i class="fa fa-angle-down"></i>
					</div>
					<div class="acordion-content" id="content-twentytwo">
						
						Yes, Buy2Let intends to perform property valuation annually.
 
					</div>
				</div>
				<div class="each-container">
					<div class="acordion" id="twentythree">
						What are my responsibilities? <i class="fa fa-angle-down"></i>
					</div>
					<div class="acordion-content" id="content-twentythree">
						This is a fully managed investment and is intended to require no investor involvement in ongoing operations.
					</div>
				</div>
				
			</div>
		</div>
		
    </div>

<script src="<?php echo base_url(); ?>assets/js/faq-accordion.js"></script>
